### ISSUE TITLE
it:titolo:openssl: syntax error in expression

### ISSUE THREAD

**Issue by gregoriopellegrino** [eniocarboni/p7m#10]
Grazie per questo tool!

Cercando di estrapolare questa fattura: 
[IT01336610587_08E8g.xml.p7m.zip](https://github.com/eniocarboni/p7m/files/3819294/IT01336610587_08E8g.xml.p7m.zip)

Ricevo questi errori:
```
p7m: line 220: it:openssl:verifica:timestamp:mancante: syntax error in expression (error token is ":openssl:verifica:timestamp:mancante")
p7m: line 220: it:openssl:verifica:errore:continuo: syntax error in expression (error token is ":openssl:verifica:errore:continuo")
p7m: line 220: it:titolo:openssl: syntax error in expression (error token is ":titolo:openssl")
 [s/n]
```

Pur selezionando "s" l'errore si ripresenta in loop.

**Comment by eniocarboni** [comment]
Ciao @gregoriopellegrino e grazie per i complimenti.
Prova a scaricare l'ultima versione di p7m che non dovrebbe dare più quel messaggio ma indicare semplicemente:

**`Formato del file p7m non riconosciuto.`**

Questo perché il tuo p7m è in formato der ma senza le intestazioni BEGIN PKCS7 ed END PKCS7.

Per risolvere velocemente vedi la mia risposta al commento sul mio articolo https://quoll.it/firma-digitale-p7m-come-estrarre-il-contenuto/#comment-44 che comunque ti riporto quì sotto:

Puoi provare quindi ad editare il file ed aggiungere in testa la riga
`-----BEGIN PKCS7-----`
ed in fondo
`-----END PKCS7-----
`
oppure a convertirlo direttamente in DER standard tramite il comando
`openssl base64 -d -in tuofile.p7m -out tuofile-convertito-der.p7m`
Se il tuo file originale è un’unica riga lunga devi aggiungere il parametro “-A”
`openssl base64 -d -A -in tuofile.p7m -out tuofile-convertito-der.p7m`

Se ritieni che sia utile implementarlo in p7m perché ci sono molte fatture in questo modo fammi sapere.

**Comment by gregoriopellegrino** [comment]
Sto lavorando con la versione 0.4 su mac, ma continua ad apparire l'errore segnalato.

Adesso analizzo i suggerimenti che mi ha indicato.

In ogni caso di tratta di una fattura di S.I.A.E., quindi penso che potrà accadere in altri casi, per altri utenti.

**Comment by eniocarboni** [comment]
Ciao @gregoriopellegrino, scusa ma su Mac che versione di Bash hai?
Nella riga 220 uso un array associativo che necessita almeno della versione 4
Prova:
`bash --version`
La versione 3 è molto indietro

**Comment by gregoriopellegrino** [comment]
`GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)`

È quella installata di default su MacOs 10.14.6 (penultima versione).

**Comment by eniocarboni** [comment]
Ok forse è un problema di licenza con il passaggio dalla GPLv2 alla GPLv3
Vedi [qui](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba)

**Comment by eniocarboni** [comment]
Nella release 0.5 dovrei aver risolto il problema sia della codifica del file che della compatibilità della versione Bash.
