### ISSUE TITLE
warning di cp che cerca di copiare .config/p7m in /tmp

### ISSUE THREAD

**Issue by drbel8** [eniocarboni/p7m#13]
il cp alla linea 1300 da uno warning nel caso in cui $xsl_file sia vuoto.
Il test -e è true perché la dir .config/p7m esiste) il cp cerca di copiare l'intera dir ma da warning perché non è cp -r
Ho sostituito il test alla linea 1299 (-e ) in -f mi sembra che ottenga lo scopo desiderato

**Comment by eniocarboni** [comment]
Ciao @drbel8 e grazie per la segnalazione.
Dovrei aver risolto il problema con l'ultimo commit.
