### ISSUE TITLE
Enhancement: Sign filesin PAdES and CAdES formats

### ISSUE THREAD

**Issue by emanuelegissi** [eniocarboni/p7m#15]
Prima di tutto desidero ringraziarti per questo utilissimo script: semplice ed essenziale.
Sarebbe molto utile se fosse possibile anche firmare in formato PAdES e CAdES impiegando la smartcard.
Se mi dai due dritte su dove cominciare, posso anche provare a contribuire del codice.
Comunque grazie!

**Comment by eniocarboni** [comment]
Ciao @emanuelegissi, 
per poter firmare, in linea di massima, si dovrebbe utilizzare il comando:
`openssl cms -nosmimecap -md sha256 -binary -nodetach -cades -outform DER -sign -signer tuocert.pem -inkey tuachiaveprivata.key -in file.pdf -out file.pdf.p7m`
dopo aver configurato il file openssl.cnf con le specifiche della tua smartcard.

Il problema principale è che il CNIPA richiede che nel pkcs#7 generato sia presente l’attributo _signingCertificateV2_ che gestisce le specifiche CMS su CAdES ed in particolar modo sulla marcatura temporale della firma.

Purtroppo, a meno che non provi la versione in sviluppo di OpenSSL (ma non ho verificato), nell'engine pks11 manca la parte di marcatura temporale e quindi non riuscirai ad avere un p7m validabile.

In rete si trovano delle patch per l'engine pkcs11 ma dovresti ricompilarti il sorgente di openssl e verificare il funzionamento.

**Comment by emanuelegissi** [comment]
Beh, mi sembra fantastico. Ci proverò di sicuro.

Firmo 100-200 documenti al giorno, con grande fatica. Appena uscirà il
nuovo OpenSSL potrò gettare via tutti quegli strumenti drammatici che mi
tocca usare (es. ArubaSign, ...) e finalmente usare uno strumento più Linux
friendly. Immagino il drag-and-drop sull'icona dello script, ed il
documento firmato viene creato nella dir di provenienza.

Per il formato PAdES, c'è qualcosa di analogo?

**Comment by eniocarboni** [comment]
Per il formato PAdES e quindi per la firma sui pdf purtroppo non posso aiutarti molto anche se credo che il problema principale sia sempre la marcatura temporale.
Cercando online "openssl pades" qualcosa potresti trovare ma è da verificare bene.

**Comment by emanuelegissi** [comment]
Grazie, provo
