### ISSUE TITLE
Convert .p7m in .asc

### ISSUE THREAD

**Issue by pfloriginale** [eniocarboni/p7m#18]
Hi Super Ennio,
today happened a strange thing...

One of my supplier send me a .p7m that once is converted, become a .asc 

I need obviusly, the .xml nested, cause I need parsify it for my accountant software... 

You'll find the file in attach.

thanks a lot!

[IT01558670780_W3662.xml.p7m.zip](https://github.com/eniocarboni/p7m/files/6661899/IT01558670780_W3662.xml.p7m.zip)

**Comment by eniocarboni** [comment]
I @pfloriginale 
your converted file .asc is an xml, just rename the file from .asc to .xml.
Unfortunately your xml invoice does not start as it should and that is with the line:

`<?xml version="1.0" encoding="utf-8"?>`

It is for this reason that the extension .asc (ascii) is added by the p7m program (the file is recognized as: type: text/plain and not type: text/xml | application/xml)

[Here](https://github.com/italia/fatturapa-testsdi/blob/master/core/schemas/Schema_del_file_xml_FatturaPA_versione_1.2_cleanup.xsd) you can see a correct invoice xml file.
