### ISSUE TITLE
Bad file p7m format

### ISSUE THREAD

**Issue by meritoskratos** [eniocarboni/p7m#20]
Ciao Enio, complimenti davvero!!! Uso il tuo script per pulire le fatture elettroniche. Tutto ok fino alla fattura in allegato. Cosa ne pensi? uso php su ubuntu 18.04 e lancio lo script in questo modo: p7m -x <FILENAME>. Ho scaricato proprio questa mattina l'ultima versione del tuo script. 

Grazie mille!!!

[IT03632460485_5ALW6.xml.zip](https://github.com/eniocarboni/p7m/files/6891834/IT03632460485_5ALW6.xml.zip)

**Comment by eniocarboni** [comment]
Ciao @meritoskratos,
 ho verificato che durante il controllo del formato base64 il check md5 fallisce in questo caso perché manca un carattere finale di controllo. il bug è in p7m e non nel tuo file.
A breve applicherò la patch per eliminare il problema.

Per ora puoi risolvere con:

`openssl base64 -d -in IT03632460485_5ALW6.xml.p7m -out IT03632460485_5ALW6_DER.xml.p7m`

e quindi con il solito comando con p7m ad esempio:

`p7m -x IT03632460485_5ALW6_DER.xml.p7m`

**Comment by eniocarboni** [comment]
Ciao @meritoskratos ho appena aggiunto la versione [0.5.4](https://github.com/eniocarboni/p7m/releases/tag/p7m_0.5.4) che risolve anche questo problema.

**Comment by meritoskratos** [comment]
Enio veramente un grande!! Grazie mille e complimenti ancora!

> Ciao @meritoskratos ho appena aggiunto la versione [0.5.4](https://github.com/eniocarboni/p7m/releases/tag/p7m_0.5.4) che risolve anche questo problema.
