### ISSUE TITLE
Mantenere nome file inalterato

### ISSUE THREAD

**Issue by TheMic** [eniocarboni/p7m#22]
Ciao Enio,
complimenti per l'ottimo strumento che hai realizzato... ormai lo uso quotidianamente ed ho rimosso Dike.

Volevo sapere se era possibile mantenere il nome del file esportato inalterato. Mi spiego meglio... ora come ora, ad esempio, quando estraggo un file XML dal P7M con questo nome: "IT06655971007_ABXfe.xml.p7m" mi ritrovo il nuovo nome file tutto in minuscolo "it06655971007_abxfe.xml"
Potresti casomai prevedere una scelta da file di configurazione. (è una piccolezza, lo so, ma a me da parecchie noie dopo quando devo ricercare qualcosa...)

Grazie mille.

**Comment by eniocarboni** [comment]
Ciao @TheMic, dovrei aver risolto il problema

**Comment by eniocarboni** [comment]
La nuova versione 0.5.5 è attiva con le ultime modifiche https://github.com/eniocarboni/p7m/releases/tag/p7m_0.5.5

**Comment by TheMic** [comment]
perfetto... funziona alla grande! Grazie!
