### ISSUE TITLE
Nuove Opzioni

### ISSUE THREAD

**Issue by ancucchi** [eniocarboni/p7m#29]
Innanzitutto grazie per il tuo programma.
Per lavoro estraggo centinaia di file dai p7m e con il tuo programma lo faccio in modalità batch.

Però volevo segnalare che se scrivo p7m -x file1.pdf.p7m, il software estrae correttamente il file1.pdf contenuto, ma se scrivo p7m -x * il software mi restituisce in rosso:

      There is no file. Check better (file1.pdf.p7m file2.pdf.p7m file3.pdf.p7m).

Ho risolto con il seguente piccolo script:

      for i in *.p7m
           do
           echo ${i}
           p7m -x "${i}"
      done

Esiste un modo migliore di chiedere a p7m di estrarre tutti i file con estensione p7m contenuti in una directory?
    
In più, essendo il pc con cui lavoro staccato dalla rete, p7m quando richiedo p7m -x file1.pdf.p7m mi restituisce:

      P7M

      Starting download the CA ... wait, please

      P7M

      Unable to download the 'CA' at this time ... try again later

      [logs]:
       --2023-07-19 16:38:26--  https://eidas.agid.gov.it/TL/TSL-IT.xml
      Resolving eidas.agid.gov.it (eidas.agid.gov.it)... failed: Temporary failure in name resolution.
      wget: unable to resolve host address ‘eidas.agid.gov.it’
      
      
      Extract the file in  './ file1.pdf'
      [tipo: application/pdf]

Non potresti mettere un'opzione che forza il NON dowload della CA?

Grazie per aver letto sin qui!

___________
**_Ancucchi_**

**Comment by eniocarboni** [comment]
Salve @ancucchi ,
  rispondo velocemente solo alla seconda parte dato che per la prima ci sarebbe bisogno di una riscrittura di parte del codice e ora non avrei molto tempo ma lo segno come cose da fare.

Se non vuoi scaricare i certificati (vengono scaricati ogni 15 gg circa e per l'esattezza ogni 1296000 secondi), basta editare o creare il file di configurazione sotto la tua HOME **_.config/p7m/p7m_config_** ed aggiungere in fondo:

`CA_OLD_TIME_SEC=315360000`

In tal modo l'aggiornamento dei certificati verranno fatti ogni 10 anni!

**Comment by eniocarboni** [comment]
Per la prima parte per ora puoi semplificare su singola linea con:

ls -Q *.p7m | xargs -n 1 p7m -x

**Comment by ancucchi** [comment]
> Salve @ancucchi , rispondo velocemente solo alla seconda parte dato che per la prima ci sarebbe bisogno di una riscrittura di parte del codice e ora non avrei molto tempo ma lo segno come cose da fare.
> 
> Se non vuoi scaricare i certificati (vengono scaricati ogni 15 gg circa e per l'esattezza ogni 1296000 secondi), basta editare o creare il file di configurazione sotto la tua HOME **_.config/p7m/p7m_config_** ed aggiungere in fondo:
> 
> `CA_OLD_TIME_SEC=315360000`
> 
> In tal modo l'aggiornamento dei certificati verranno fatti ogni 10 anni!

Perfetto. Ho connesso la macchina per una volta, ha scaricato ciò che doveva e adesso fila come un razzo (oggi sto esportando il contenuto di decine di migliaia di p7m e il risparmio di tempo è enorme).

> Per la prima parte per ora puoi semplificare su singola linea con:
> 
> `ls -Q *.p7m | xargs -n 1 p7m -x`

Perfetto Bis.

Grazie della tua pronta disponibilità!

______________________________________
**_Ancucchi_**
