### ISSUE TITLE
Errore nel caricamento del foglio di stile: Interpretazione del foglio di stile XSLT non riuscita.

### ISSUE THREAD

**Issue by thekurtz** [eniocarboni/p7m#30]
Dopo aver estratto con p7m -x, provo  a visualizzare una fattura aprendo il miniserver locale, Firefox mostra
Errore nel caricamento del foglio di stile: Interpretazione del foglio di stile XSLT non riuscita.

**Comment by thekurtz** [comment]
nella funzione p7mplugin() quando la "$testif_xmlstylesheet" è non nulla, non viene aggiornata, ma può capitare che quanto già presente nell xml non combaci con il $xsl_file aggiornato. Nel mio caso c'era v1.2, mentre viene scaricata l aversione 1.2.1. Si può  quindi aggiungere un controllo se il "$testif_xmlstylesheet" è non nullo sostituisce comunque la versione con quella in $xsl_file. 
Come ho riportato qui sotto.

p7mplugin() {
	local file=$1
	local testif_fatturaelettronica=$(grep -E '<FatturaElettronicaHeader' "$file")
	local t=`file -b --mime-type "$file"`
	if [ -n "$t" -a "$t" = 'application/xml' ]; then
		t='text/xml'
	fi
	if [ -n "$testif_fatturaelettronica" ]; then
		t='text/xml'
	fi
			local version
	local tag_FatturaElettronica=$(grep -E '<(.*:)?FatturaElettronica ' "$file")
	local testif_xmlstylesheet=$(grep -E 'xml-stylesheet' $file)
	if [ "$t" = 'text/xml' -a -n "$testif_fatturaelettronica" ]; then
		# check if fattura elettronica
		# found version and make all lowercase
		version=$(echo $tag_FatturaElettronica | sed -e 's/^.*versione="\([^"]*\).*$/\1/' | tr '[A-Z]' '[a-z]')
		getxslenvs $version
		if ! [ -z "$testif_xmlstylesheet" ]; then
			sed -i 's/[^"]*\.xsl/'$xsl_file'/' "$file"
		else [ -z "$testif_xmlstylesheet" ] 
			sed -i 's/\(<\([[:alnum:]]*:\)*FatturaElettronica \)/<\?xml-stylesheet type="text\/xsl" href="'$xsl_file'"\?>\1/' "$file"
		fi
		copyxslfile "$version" "$(dirname $file)"
		IS_FATTURA=1

**Comment by eniocarboni** [comment]
Salve @thekurtz,
ho fatto la modifica avanzando anche la versione dell'xslt alla 1.2.2 come da [specifica  fatturaPa](https://www.fatturapa.gov.it/it/norme-e-regole/documentazione-fattura-elettronica/formato-fatturapa/) dell'1/2/2024.

Per i nuovi xslt vedi il README nella [Nota3](https://github.com/eniocarboni/p7m#nota-3-fatture-elettroniche).
