### ISSUE TITLE
Verification failure

### ISSUE THREAD

**Issue by frnmst** [eniocarboni/p7m#4]
Salve ancora,
ho un problema con la verifica di una firma

p7m (e openssl) mi ritorna questo:

```
------- Details-------
Verification failure
140150889910912:error:04091068:rsa routines:int_rsa_verify:bad signature:crypto/rsa/rsa_sign.c:220:
140150889910912:error:21071069:PKCS7 routines:PKCS7_signatureVerify:signature failure:crypto/pkcs7/pk7_doit.c:1037:
140150889910912:error:21075069:PKCS7 routines:PKCS7_verify:signature failure:crypto/pkcs7/pk7_smime.c:353:
----------------------
```

Ovviamente ho provato anche con:

    $ openssl smime -in ~/documento.xml.p7m  -inform DER -verify -CAfile ~/.config/p7m/ca.pem  -out ~/documento.xml

Non trovo molto in giro. Qualche idea?
Grazie

**Comment by eniocarboni** [comment]
Ciao Franco,
 da quel che capisco sembra proprio che la firma non sia valida oppure non hai il certificato associato di chi ha firmato in ~/.config/p7m/ca.pem. 
Per prima cosa prova a rigenerare il ca.pem (anche se penso che l'hai già fatto) con p7m -p

Se nulla cambia direi di utilizzare openssl con l'opzione -noverify (supponiamo che il p7m sia in DER) come:
`openssl smime -verify -noverify -in ~/documento.xml.p7m  -inform DER -out ~/documento.xml`
Per fare ulteriori controlli sul certificato prova ad estrarlo e verificare il contenuto:
`openssl pkcs7 -inform DER -in ~/documento.xml.p7m -print_certs -text`

**Comment by frnmst** [comment]
Ciao Enio,
grazie per la risposta.

Sì, ho rigenerato il file dei certificati usando la nuova lista visto che quel particolare certificato non c'era in quella vecchia. Ovviamente ho fatto `$ rm -rf ~/.config/p7m` prima. 

Spiego brevemente il problema: si tratta di aprire fatture arrivate dal "sistema di interscambio". I file arrivano su PEC e fino ad ora sono sempre stati `xml.p7m`. Quindi riesco a vedere il contenuto del file firmato anche senza `openssl -noverify` (la firma è un parametro legale quindi è sempre meglio controllarla)... 

Ho fatto un controllo con 

    openssl pkcs7 -inform DER -in ~/documento.xml.p7m -print -text

ed ho guardato i campi `issuer`. Il certificato e' lo stesso di quello usato in un altro documento. Quindi penso possa essere esclusivamente un problema di firma.

Comunque si tratta di 1 documento solo. Con tutti gli altri funziona.

**Comment by pfloriginale** [comment]
Io ho lo stesso problema con un documento solo

uso
`openssl smime -decrypt -in nome_file.p7m -inform DER -verify -noverify -out nomefile_estratto.xml`


Me lo estrae correttamente ma mi genera l'errore

> Verification failure
> 34359738384:error:04091068:rsa routines:int_rsa_verify:bad signature:crypto/rsa/rsa_sign.c:220:
> 34359738384:error:21071069:PKCS7 routines:PKCS7_signatureVerify:signature failure:crypto/pkcs7/pk7_doit.c:1041:
> 34359738384:error:21075069:PKCS7 routines:PKCS7_verify:signature failure:crypto/pkcs7/pk7_smime.c:353:

**Comment by eniocarboni** [comment]
Ciao @pfloriginale, credo che il problema sia lo stesso dell'issue #7

**Comment by pfloriginale** [comment]
Grazie,
ho risolto in modo spartano facendo cosi
- faccio una prova con openssl smime
- se faccile proco con openssl cms
- se fallisce provono con base64

Per il momento riesco a trattare tutti i p7m, ma mi rendo conto essere un workaround da vero pdm

**Comment by eniocarboni** [comment]
Ciao @pfloriginale, ecco come faccio in p7m https://github.com/eniocarboni/p7m/blob/master/bin/p7m#L955..L1000
