### ISSUE TITLE
File non estratto

### ISSUE THREAD

**Issue by gregoriopellegrino** [eniocarboni/p7m#5]
Gentile Enio,
grazie per il tuo lavoro. Lo script è molto utile. Ti segnalo un problema che ho con un file: 
[IT01879020517_kaHc7.xml.p7m.zip](https://github.com/eniocarboni/p7m/files/2833697/IT01879020517_kaHc7.xml.p7m.zip)

Lo script non lo estrae e non segnala alcun errore a video.

Grazie,
Gregorio

**Comment by eniocarboni** [comment]
Ciao @gregoriopellegrino,
il problema è che il p7m non è nel formato giusto ma è encodato base64 come se fosse un allegato email non estratto o come se provenisse da un campo binario di un file xml.
Mi faresti sapere se questo è uno standard e quindi ci sono altri file come questo e soprattutto da dove proviene in modo tale da capire se implementarlo nel software p7m.
Per risolvere il tuo problema basta che segui la [risposta al commento che ho dato qui](https://quoll.it/firma-digitale-p7m-come-estrarre-il-contenuto/#comment-44).

**Comment by gregoriopellegrino** [comment]
Per il momento due fornitori ho visto che le inviano in questo modo allo SDI (le sto scaricando da lì). Uno dei due è Aruba, quindi penso possa essere un problema comune a molti.

Intanto sistemo con la tua indicazione.

Grazie,
Gregorio

**Comment by eniocarboni** [comment]
Ciao @gregoriopellegrino, dovrei aver risolto con questo commit il problema dei p7m encodati con base64.
