### ISSUE TITLE
Errore se estensione in maiuscolo

### ISSUE THREAD

**Issue by gregoriopellegrino** [eniocarboni/p7m#6]
Caro Enio,
ti segnalo che il programma restituisce errore se gli sottopongo un file con estensione maiuscola .P7M, mi riporta:
```
Attenzione                                                                                                                                                    
Bisogna passare un file con estensione .p7m come parametro
```
Poco male, rinomino il file, ma per altri potrebbe essere un problema.

Grazie,
Gregorio

**Comment by eniocarboni** [comment]
Grazie @gregoriopellegrino,
ho appena fatto il commit per risolvere il problema
